export interface UserTranslations {
  common: {
    appName: string;
    loading: string;
    error: string;
    success: string;
    cancel: string;
    confirm: string;
    save: string;
    delete: string;
    edit: string;
    back: string;
    next: string;
    prev: string;
    page: string; // uses {page}
    search: string;
    refresh: string;
    copy: string;
    copied: string;
    close: string;
    yes: string;
    no: string;
    na: string;
  };

  home: {
    title: string;
    subtitle: string;
    heroTitle: string;
    heroSubtitle: string;
    featureNoSignup: string;
    featureRecoverKey: string;
    featureNoAttachments: string;
    howItWorks: string;
    howStepCreate: string;
    howStepReceive: string;
    howStepClaimRecover: string;
    formTitle: string;
    formSubtitle: string;
    modeRandom: string;
    modeManual: string;
    username: string;
    usernamePlaceholder: string;
    usernameAutoGenerated: string;
    domain: string;
    createButton: string;
    randomButton: string;
    claimButton: string;
    recoverButton: string;
    usernameRequired: string;
    usernameInvalid: string;
    createFailed: string;
    retryAfter: string; // uses {seconds}
    turnstileNotConfigured: string;
    turnstileRequired: string;
  };

  inbox: {
    title: string;
    sent: string;
    unread: string;
    unreadCount: string; // uses {count}
    keyExpires: string;
    refreshButton: string;
    renewButton: string;
    exitButton: string;
    searchPlaceholder: string;
    unreadOnly: string;
    loadingList: string;
    emptyList: string;
    loadingMessage: string;
    selectMessage: string;
    noSubject: string;
    from: string;
    received: string;
    htmlView: string;
    textView: string;
    loadExternal: string;
    externalBlocked: string;
    externalAllowed: string;
    renewed: string;
    renewedExpires: string; // uses {time}
    renewFailed: string;
    loadFailed: string;
  };

  compose: {
    title: string;
    subtitle: string;
    newMessage: string;
    reply: string;
    replyAll: string;
    forward: string;
    mailbox: string;
    mode: string;
    thread: string;
    recipients: string;
    to: string;
    cc: string;
    bcc: string;
    subject: string;
    fromName: string;
    description: string;
    linkUrl: string;
    videoUrl: string;
    imageUrl: string;
    inspector: string;
    formula: string;
    markdown: string;
    linkCard: string;
    send: string;
    bodyTooLong: string;
    messageQueued: string;
    messageSent: string;
    loadFailed: string;
    sendFailed: string;
  };

  claim: {
    title: string;
    subtitle: string;
    emailLabel: string;
    emailPlaceholder: string; // uses {domain}
    turnstileNotConfigured: string;
    turnstileRequired: string;
    claimButton: string;
    claimFailed: string;
    keyDialogTitle: string;
    keyExpires: string; // uses {time}
    keySavedConfirm: string;
    keyHint: string;
    continueButton: string;
    recoverButton: string;
  };

  recover: {
    title: string;
    subtitle: string;
    usernameLabel: string;
    usernamePlaceholder: string;
    domainLabel: string;
    keyLabel: string;
    keyPlaceholder: string;
    recoverButton: string;
    recoverFailed: string;
    keyExpiresNotice: string; // uses {time}
    turnstileNotConfigured: string;
    turnstileRequired: string;
  };

  errors: {
    invalidRequest: string;
    unauthorized: string;
    sessionExpired: string;
    invalidCredentials: string;
    mailboxNotFound: string;
    mailboxExists: string;
    mailboxAlreadyClaimed: string;
    mailboxDestroyed: string;
    invalidUsername: string;
    keyExpired: string;
    rateLimited: string;
    turnstileFailed: string;
    internalError: string;
  };

  language: {
    label: string;
    enUS: string;
    zhCN: string;
    zhTW: string;
    frFR: string;
    deDE: string;
    esES: string;
    jaJP: string;
  };

  theme: {
    label: string;
    light: string;
    dark: string;
    system: string;
  };

  sound: {
    label: string;
    on: string;
    off: string;
  };

  footer: {
    copyright: string; // uses {year}
    brandName: string;
    officialSiteAria: string;
    githubLabel: string;
    githubAria: string;
    licenseLabel: string;
    poweredByPrefix: string;
    poweredBySuffix: string;
    cloudflareAria: string;
  };
}
