export interface UserTranslations {
  common: {
    appName: string;
    loading: string;
    error: string;
    success: string;
    cancel: string;
    confirm: string;
    save: string;
    delete: string;
    edit: string;
    back: string;
    next: string;
    prev: string;
    page: string; // uses {page}
    search: string;
    refresh: string;
    copy: string;
    copied: string;
    close: string;
    yes: string;
    no: string;
    na: string;
  };

  home: {
    title: string;
    subtitle: string;
    heroTitle: string;
    heroSubtitle: string;
    featureNoSignup: string;
    featureRecoverKey: string;
    featureNoAttachments: string;
    howItWorks: string;
    howStepCreate: string;
    howStepReceive: string;
    howStepClaimRecover: string;
    formTitle: string;
    formSubtitle: string;
    modeRandom: string;
    modeManual: string;
    username: string;
    usernamePlaceholder: string;
    usernameAutoGenerated: string;
    domain: string;
    createButton: string;
    randomButton: string;
    claimButton: string;
    recoverButton: string;
    usernameRequired: string;
    usernameInvalid: string;
    createFailed: string;
    retryAfter: string; // uses {seconds}
  };

  inbox: {
    title: string;
    unread: string;
    unreadCount: string; // uses {count}
    keyExpires: string;
    refreshButton: string;
    renewButton: string;
    exitButton: string;
    searchPlaceholder: string;
    unreadOnly: string;
    loadingList: string;
    loadingMessage: string;
    selectMessage: string;
    noSubject: string;
    from: string;
    received: string;
    htmlView: string;
    textView: string;
    loadExternal: string;
    renewed: string;
    renewedExpires: string; // uses {time}
    renewFailed: string;
    loadFailed: string;
  };

  claim: {
    title: string;
    subtitle: string;
    emailLabel: string;
    emailPlaceholder: string; // uses {domain}
    turnstileNotConfigured: string;
    turnstileRequired: string;
    claimButton: string;
    claimFailed: string;
    keyDialogTitle: string;
    keyExpires: string; // uses {time}
    keySavedConfirm: string;
    keyHint: string;
    continueButton: string;
    recoverButton: string;
  };

  recover: {
    title: string;
    subtitle: string;
    usernameLabel: string;
    usernamePlaceholder: string;
    domainLabel: string;
    keyLabel: string;
    keyPlaceholder: string;
    recoverButton: string;
    recoverFailed: string;
    keyExpiresNotice: string; // uses {time}
  };

  errors: {
    invalidRequest: string;
    unauthorized: string;
    sessionExpired: string;
    invalidCredentials: string;
    mailboxNotFound: string;
    mailboxExists: string;
    mailboxAlreadyClaimed: string;
    mailboxDestroyed: string;
    invalidUsername: string;
    keyExpired: string;
    rateLimited: string;
    turnstileFailed: string;
    internalError: string;
  };

  language: {
    label: string;
    enUS: string;
    zhCN: string;
    zhTW: string;
  };

  theme: {
    label: string;
    light: string;
    dark: string;
    system: string;
  };
}

